# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Wasco-Wishram spellchecker"
wac = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Wasco-Wishram, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
wac = "TRANSLATE: A spellchecker for Wasco-Wishram, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.wac"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"

[package.speller]
name = "Wasco-Wishram"
version = "0.1.0"

[package.grammar]
name = "Wasco-Wishram"
version = "0.1.0"

[package.tts-text-proc]
name = "Wasco-Wishram"
version = "0.1.0"
