template = ""
rev_id = 265
template_sha = "55c74340aa57ef2b38d3f84b2a9790e969781f56"

[replacements]
__GLOTTOLOG_ID__ = "wasc1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wac"
__UND2C__ = "wac"
__UNDEFINED__ = "Wasco-Wishram"
__UND__ = "wac"
