template = ""
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "wasc1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wac"
__UND2C__ = "wac"
__UNDEFINED__ = "Wasco-Wishram"
__UND__ = "wac"
